title: Blog & Portfolio
tagline: Student eager to learn about Machine Learning and Deep Learning
# email:  # Update your email
description: Personal blog covering coding, projects, and learning journey.
# github_username: fra-git 

# -----------------------------------------------------------------------------
# Theme Setup (CRITICAL - DO NOT CHANGE THESE LINES)
# -----------------------------------------------------------------------------
theme: minima
plugins:
  - jekyll-feed
  
# -----------------------------------------------------------------------------
# GitHub Pages Setup (Keep this structure)
# -----------------------------------------------------------------------------
baseurl: "/blog"
url: "https://fra-git.github.io"

# -----------------------------------------------------------------------------
# Author Profile Settings (Sidebar - UPDATE THESE)
# -----------------------------------------------------------------------------
avatar: /assets/img/profile.jpg # You will upload this image later
locale: en
social:
  github: fra-git
  #linkedin: your_linkedin_handle 
  #location: My Current City, Country # e.g., Washington, DC

